//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class Localidade
    {
        public int Id { get; set; }
        public string Nombre { get; set; }
        public string IdProv { get; set; }
        public Nullable<int> NumHab { get; set; }
    
        public virtual Provincia Provincia { get; set; }

        public Localidade(){} //Necesario para Entity

        // CONSTRUCTOR PARA AÑADIR NUEVA LOCALIDAD EN BD (EJ. 5)
        public Localidade(int id, string nombre, string idProvincia, int? nHabitantes, Provincia provincia) 
        {
            Id = id;
            Nombre = nombre;
            IdProv = idProvincia;
            NumHab = nHabitantes;
            Provincia = provincia;
        }
    }
}
